#!/usr/bin/env bash
# verify-smart-d4.sh — accel_smart D4 kernel-side validation.
#
# What this script checks (additive on top of D2 — D2 passed already):
#
#   1. file integrity
#   2. kernel + BTF + bpftool sanity
#   3. accel binary boots cleanly with smart in the loaded list
#   4. NEW: tc-bpf companion `smart_dup` is loaded into the kernel
#      (verifier accepted it; D3 BPF C compiled OK and produced a
#      kernel-loadable program). At D4 we don't yet attach it to a
#      tc/egress hook — that's D5 work — so we look for it in
#      `bpftool prog show`, NOT in `tc filter show`.
#   5. NEW: `smart_link_state` is shared between the struct_ops side
#      and the dup side (the reuse_fd plumbing in load_smart). We
#      verify exactly ONE map named `smart_link_state` exists in the
#      kernel — if reuse_fd had failed silently we'd see two.
#   6. NEW: clean shutdown — after `./accel stop`, `smart_dup` and
#      `smart_link_state` are gone from the kernel (no zombie state).
#
# What this script does NOT check yet:
#   * tc/egress filter actually attached — D5 wires that in cli.rs.
#   * Live traffic going through the cong_control / dup paths — D6.
#
# Subcommands:
#   ./verify-smart-d4.sh           — full D4 test (default)
#   ./verify-smart-d4.sh diag      — dump the relevant kernel state
#                                    (useful for follow-up debugging)
#   ./verify-smart-d4.sh stop      — clean stop helper
#
# Run as root (`sudo ./verify-smart-d4.sh`).

set -euo pipefail

EXPECTED_BIN_MD5="44dc6ce7b920531be115c8805d8874bc"

cd "$(dirname "$0")"

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "✗ must run as root (sudo)" >&2
        exit 1
    fi
}

# Count BPF objects matching a label substring. We keep the parsing
# tolerant of bpftool's slightly-different output across versions:
# both v7.1 ("123: cgroup_skb  name foo") and v7.4 work the same way
# under our grep-by-name.
prog_count() {
    local name="$1"
    bpftool prog show 2>/dev/null | awk -v n="$name" '$0 ~ "name " n " "  { c++ } END { print c+0 }'
}

map_count() {
    local name="$1"
    bpftool map show 2>/dev/null | awk -v n="$name" '$0 ~ "name " n " " { c++ } END { print c+0 }'
}

cmd_diag() {
    require_root
    echo "── bpftool prog show (smart_*) ──"
    bpftool prog show 2>/dev/null | grep -E "name (smart_|brutal_|cubictcp_|bictcp_)" || true
    echo
    echo "── bpftool map show (smart_*) ──"
    bpftool map show 2>/dev/null | grep -E "name (smart_|brutal_)" || true
    echo
    echo "── bpftool struct_ops show ──"
    bpftool struct_ops show 2>/dev/null || true
    echo
    echo "── tc filter show dev <iface> egress ──"
    for iface in $(ls /sys/class/net | grep -v '^lo$'); do
        echo "  [$iface]"
        tc filter show dev "$iface" egress 2>/dev/null | sed 's/^/    /' || true
    done
}

cmd_stop() {
    require_root
    ./accel stop 2>/dev/null || true
    sleep 1
    pkill -9 -x accel 2>/dev/null || true
}

cmd_default() {
    require_root

    echo "=== accel_smart D4 kernel-side validation ==="
    echo

    # 1. file integrity
    echo "[1/6] file integrity"
    if [ ! -f accel ]; then
        echo "  ✗ missing: accel" >&2
        exit 1
    fi
    local got
    got=$(md5sum accel | awk '{print $1}')
    if [ "$got" != "$EXPECTED_BIN_MD5" ]; then
        echo "  ✗ accel md5 mismatch" >&2
        echo "    got:      $got" >&2
        echo "    expected: $EXPECTED_BIN_MD5" >&2
        exit 1
    fi
    echo "  accel: $got ✓"
    echo

    # 2. kernel + bpftool sanity
    echo "[2/6] kernel + BTF + bpftool"
    echo "  kernel: $(uname -r)"
    if [ ! -f /sys/kernel/btf/vmlinux ]; then
        echo "  ✗ no /sys/kernel/btf/vmlinux" >&2
        exit 1
    fi
    echo "  BTF: $(stat -c%s /sys/kernel/btf/vmlinux) bytes ✓"
    if ! command -v bpftool >/dev/null; then
        echo "  ✗ bpftool not found — apt install bpftool linux-tools-generic" >&2
        exit 1
    fi
    echo "  bpftool: $(bpftool version 2>&1 | head -1)"
    echo

    # 3. clean slate + write minimal acc.conf
    echo "[3/6] clean slate + acc.conf"
    cmd_stop
    if [ -f acc.conf ] && [ ! -f acc.conf.d4-backup ]; then
        cp acc.conf acc.conf.d4-backup
        echo "  backed up existing acc.conf → acc.conf.d4-backup"
    fi
    cat > acc.conf <<'CONF'
# generated by verify-smart-d4.sh
algorithm = "accel_cubic"

[runtime]
socket = ""
CONF
    echo "  acc.conf written"
    echo

    # 4. start accel + verify smart loaded line
    echo "[4/6] start accel + verify load"
    rm -f /tmp/accel-d4.log
    local dmesg_before
    dmesg_before=$(dmesg | wc -l)

    ./accel > /tmp/accel-d4.log 2>&1 &
    local pid=$!
    sleep 4

    if ! kill -0 "$pid" 2>/dev/null; then
        echo "  ✗ accel exited prematurely. log:" >&2
        echo "  ----"
        cat /tmp/accel-d4.log
        echo "  ----"
        echo "  dmesg slice:"
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        exit 1
    fi

    local loaded_line
    loaded_line=$(grep -E "^  loaded: " /tmp/accel-d4.log | head -1 || true)
    if [ -z "$loaded_line" ]; then
        echo "  ✗ never reached 'loaded:' line. log:" >&2
        cat /tmp/accel-d4.log
        cmd_stop
        exit 1
    fi
    if echo "$loaded_line" | grep -q accel_smart; then
        echo "  $loaded_line"
        echo "  ✓ accel_smart in loaded list"
    else
        echo "  ✗ accel_smart NOT in loaded list — D2 regression" >&2
        echo "  $loaded_line"
        echo "  --- accel log ---"
        cat /tmp/accel-d4.log
        echo "  --- dmesg slice ---"
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        cmd_stop
        exit 1
    fi
    echo

    # 5. NEW for D4: tc-bpf companion + reuse_fd map sharing
    echo "[5/6] tc-bpf companion in kernel (D4 verifier + reuse_fd)"

    local dup_progs
    dup_progs=$(prog_count smart_dup)
    if [ "$dup_progs" -ge 1 ]; then
        echo "  ✓ smart_dup BPF program loaded (count=$dup_progs)"
        bpftool prog show 2>/dev/null | awk '/name smart_dup/{print "    " $0}' | head -3
    else
        echo "  ✗ smart_dup BPF program NOT loaded — D3 verifier rejected" >&2
        echo "  --- accel log warnings ---"
        grep -E "warning:" /tmp/accel-d4.log | head -10 || true
        echo "  --- dmesg slice ---"
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        cmd_stop
        exit 1
    fi

    local link_state_maps
    link_state_maps=$(map_count smart_link_state)
    if [ "$link_state_maps" -eq 1 ]; then
        echo "  ✓ smart_link_state map count=1 (reuse_fd worked)"
    elif [ "$link_state_maps" -eq 2 ]; then
        echo "  ✗ smart_link_state map count=2 — reuse_fd FAILED" >&2
        echo "    (struct_ops + tc-bpf each created their own map; they're" >&2
        echo "     decoupled, so LOSSY signals would never reach the dup prog)" >&2
        bpftool map show 2>/dev/null | grep smart_link_state
        cmd_stop
        exit 1
    else
        echo "  ⚠ smart_link_state map count=$link_state_maps (unexpected)"
        bpftool map show 2>/dev/null | grep smart_link_state || true
    fi

    # struct_ops registration sanity (regression: same as D2)
    if bpftool struct_ops show 2>/dev/null | grep -q accel_smart; then
        echo "  ✓ accel_smart struct_ops registered"
    else
        echo "  ⚠ accel_smart not in 'bpftool struct_ops show' (kernel may be GC'ing — fine)"
    fi
    echo

    # 6. clean shutdown
    echo "[6/6] clean shutdown"
    ./accel stop 2>/dev/null || true
    # accel may take a beat to clean up. Wait up to 8s for the dup prog
    # to disappear (kernel may pin briefly via tc qdisc).
    local i=0
    while [ "$i" -lt 8 ]; do
        if [ "$(prog_count smart_dup)" -eq 0 ] && \
           [ "$(map_count smart_link_state)" -eq 0 ]; then
            break
        fi
        sleep 1
        i=$((i+1))
    done

    local final_progs final_maps
    final_progs=$(prog_count smart_dup)
    final_maps=$(map_count smart_link_state)
    if [ "$final_progs" -eq 0 ] && [ "$final_maps" -eq 0 ]; then
        echo "  ✓ smart_dup + smart_link_state cleaned up"
    else
        echo "  ⚠ residual after stop: smart_dup=$final_progs smart_link_state=$final_maps"
        echo "    (could be kernel GC lag with active sockets pinning state — see"
        echo "     accel README §12.5)"
    fi
    echo

    if kill -0 "$pid" 2>/dev/null; then
        kill -INT "$pid" 2>/dev/null || true
        sleep 1
    fi

    echo "=== D4 KERNEL VALIDATION PASS ==="
    echo
    echo "Report verbatim to architect:"
    echo "  - 'D4 PASS'"
    echo "  - kernel: $(uname -r)"
    echo "  - loaded line: $loaded_line"
    echo "  - smart_dup count after start: $dup_progs"
    echo "  - smart_link_state map count: $link_state_maps"
}

case "${1:-default}" in
    default) cmd_default ;;
    diag)    cmd_diag ;;
    stop)    cmd_stop ;;
    *)
        echo "usage: $0 [default|diag|stop]" >&2
        exit 2
        ;;
esac
