#!/usr/bin/env bash
# verify-smart-d2.sh — accel_smart D2 verifier acceptance test (path A).
#
# What this script does:
#   1. md5 sanity on the accel binary.
#   2. Writes a minimal acc.conf with `algorithm = "accel_cubic"`. We
#      pick cubic (not smart) as the *target* on purpose — D2 is about
#      proving the kernel verifier accepts accel_smart's BPF programs,
#      not yet about routing live traffic through it. accel always
#      tries to load every algorithm in `all_loaders()` at startup, so
#      smart's verifier path is exercised independent of which one the
#      sysctl ends up pointing at.
#   3. Starts `sudo ./accel` in the background, captures startup log.
#   4. Looks for `loaded: ... accel_smart ...` in the log. PASS.
#      If accel_smart is missing from the loaded list, prints the
#      ebpf_loader warning + a dmesg slice covering the startup window
#      (kernel verifier output ends up there).
#   5. Stops accel cleanly and restores any prior config.
#
# Why path A (rather than the original `bpftool struct_ops register
# accel_smart.bpf.o`):
#   The system bpftool on Debian 12 is v7.1 / libbpf 1.1, which does
#   NOT understand the `.struct_ops.link` ELF section (added in libbpf
#   1.2). It silently skips that section, then tries to load smart_init
#   as a bare program, and the kernel returns -ENOTSUPP without the
#   verifier ever processing a single instruction. accel binary's
#   bundled libbpf-rs 0.26.2 (libbpf 1.4+) parses .struct_ops.link
#   correctly and goes through the actual verifier path — exactly the
#   path the production D4 loader will use.
#
# Subcommands:
#   ./verify-smart-d2.sh           — full verifier test (default)
#   ./verify-smart-d2.sh status    — query a running accel
#   ./verify-smart-d2.sh stop      — `./accel stop` (cleanup helper)
#
# Run as root (`sudo ./verify-smart-d2.sh`).

set -euo pipefail

EXPECTED_BIN_MD5="f374a1cb6a3d576feb8092261a9fc678"

cd "$(dirname "$0")"

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "✗ must run as root (sudo)" >&2
        exit 1
    fi
}

cmd_status() {
    require_root
    ./accel status
}

cmd_stop() {
    require_root
    ./accel stop || true
}

cmd_default() {
    require_root

    echo "=== accel_smart D2 verifier test ==="
    echo

    # 1. file integrity
    echo "[1/6] file integrity"
    if [ ! -f accel ]; then
        echo "  ✗ missing: accel" >&2
        exit 1
    fi
    local got
    got=$(md5sum accel | awk '{print $1}')
    if [ "$got" != "$EXPECTED_BIN_MD5" ]; then
        echo "  ✗ accel md5 mismatch" >&2
        echo "    got:      $got" >&2
        echo "    expected: $EXPECTED_BIN_MD5" >&2
        exit 1
    fi
    echo "  accel: $got ✓"
    echo

    # 2. kernel sanity
    echo "[2/6] kernel + BTF"
    echo "  kernel: $(uname -r)"
    if [ ! -f /sys/kernel/btf/vmlinux ]; then
        echo "  ✗ no /sys/kernel/btf/vmlinux — CONFIG_DEBUG_INFO_BTF=y missing" >&2
        exit 1
    fi
    echo "  BTF: $(stat -c%s /sys/kernel/btf/vmlinux) bytes ✓"
    echo

    # 3. clean slate (no prior accel running, no stale registrations)
    echo "[3/6] clean slate"
    if pgrep -x accel >/dev/null 2>&1; then
        echo "  prior accel running — stopping"
        ./accel stop || true
        sleep 1
        pkill -9 -x accel 2>/dev/null || true
        sleep 1
    fi
    if command -v bpftool >/dev/null && bpftool struct_ops show 2>/dev/null \
            | grep -qE "accel_(cubic|brutal|smart)"; then
        echo "  prior accel_* struct_ops still registered (will be overridden by accel)"
    fi
    echo "  done"
    echo

    # 4. write minimal acc.conf
    echo "[4/6] writing acc.conf (target = accel_cubic, smart still loaded)"
    if [ -f acc.conf ] && [ ! -f acc.conf.d2-backup ]; then
        cp acc.conf acc.conf.d2-backup
        echo "  backed up existing acc.conf → acc.conf.d2-backup"
    fi
    cat > acc.conf <<'CONF'
# generated by verify-smart-d2.sh
# target = cubic so D2 doesn't depend on a [smart] section (D4)
algorithm = "accel_cubic"

[runtime]
socket = ""
CONF
    echo "  acc.conf written"
    echo

    # 5. start accel briefly and capture startup banner
    echo "[5/6] starting accel — kernel verifier runs at load_all()"
    rm -f /tmp/accel-d2.log
    local dmesg_before
    dmesg_before=$(dmesg | wc -l)

    ./accel > /tmp/accel-d2.log 2>&1 &
    local pid=$!
    # accel needs a moment to load + register all algorithms.
    sleep 4

    if ! kill -0 "$pid" 2>/dev/null; then
        echo "  ✗ accel exited prematurely. log:" >&2
        echo "  ----" >&2
        cat /tmp/accel-d2.log
        echo "  ----" >&2
        echo "  dmesg slice:" >&2
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        exit 1
    fi
    echo "  accel pid=$pid"
    echo

    # 6. check the startup log for accel_smart in the loaded list
    echo "[6/6] checking 'loaded:' line for accel_smart"
    local loaded_line
    loaded_line=$(grep -E "^  loaded: " /tmp/accel-d2.log | head -1 || true)
    if [ -z "$loaded_line" ]; then
        echo "  ✗ never reached the 'loaded:' line — accel must have failed early" >&2
        echo "  ---- accel log ----"
        cat /tmp/accel-d2.log
        echo "  ---- dmesg slice ----"
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        ./accel stop || kill -INT "$pid" 2>/dev/null || true
        exit 1
    fi
    echo "  $loaded_line"

    if echo "$loaded_line" | grep -q accel_smart; then
        echo "  ✓ accel_smart appears in loaded list — kernel verifier ACCEPTED"
        local pass=1
    else
        echo "  ✗ accel_smart NOT in loaded list" >&2
        echo "  ---- ebpf_loader warnings (verifier rejection lives here) ----"
        grep -E "warning: accel_smart" /tmp/accel-d2.log || \
            echo "  (no smart-specific warning — full log below)"
        echo "  ---- full accel log ----"
        cat /tmp/accel-d2.log
        echo "  ---- dmesg verifier slice ----"
        dmesg | tail -n +"$((dmesg_before+1))" | tail -80
        local pass=0
    fi
    echo

    # cleanup: stop accel cleanly so sysctl is restored
    echo "stopping accel..."
    ./accel stop || true
    sleep 2
    if kill -0 "$pid" 2>/dev/null; then
        kill -INT "$pid" 2>/dev/null || true
        sleep 1
    fi

    if [ "${pass:-0}" -eq 1 ]; then
        echo
        echo "=== D2 VERIFIER TEST PASS ==="
        echo
        echo "Report verbatim to architect:"
        echo "  - 'D2 PASS'"
        echo "  - kernel: $(uname -r)"
        echo "  - the loaded line: $loaded_line"
    else
        echo
        echo "=== D2 VERIFIER TEST FAIL ==="
        echo
        echo "Copy the output above (warnings + dmesg slice) to architect."
        echo "DO NOT modify accel_smart.bpf.c locally — verifier loops are"
        echo "layered (each fix can reveal the next). PROJECT_CONTEXT §5.4."
        exit 1
    fi
}

case "${1:-default}" in
    default) cmd_default ;;
    status)  cmd_status ;;
    stop)    cmd_stop ;;
    *)
        echo "usage: $0 [default|status|stop]" >&2
        exit 2
        ;;
esac
